### ISSUE TITLE
Quast output includes N90 / L90 metrics but parse_quast_report.py expects N75 / L75 metrics

### ISSUE THREAD

**Issue by stroehleina** [BCCDC-PHL/dragonflye-nf#1]
Hi,
thanks for providing this `nextflow` wrapper for `dragonflye`. I ran into an issue where the `QUAST` output has N90 / L90 metrics but the `parse_quast_report.py` script expects N75 / L75 metrics and thus falls over.

```
Command error:
  Traceback (most recent call last):
    File "/home/astroehlein/bin/dragonflye-nf/bin/parse_quast_report.py", line 128, in <module>
      main()
    File "/home/astroehlein/bin/dragonflye-nf/bin/parse_quast_report.py", line 120, in main
      report = parse_transposed_quast_report(args.transposed_quast_report)
    File "/home/astroehlein/bin/dragonflye-nf/bin/parse_quast_report.py", line 69, in parse_transposed_quast_report
      r[field_lookup[f]] = row[f]
  KeyError: 'N75'
```

`~/.conda/envs/dragonflye-nf/bin/quast --version`
`QUAST v5.2.0`

I'll submit a PR to resolve this.

**Comment by dfornika** [comment]
Sorry but I'm not able to reproduce this. When I run the pipeline I get these headers in the QUAST output:

```
Assembly
# contigs (>= 0 bp)
# contigs (>= 1000 bp)
# contigs (>= 5000 bp)
# contigs (>= 10000 bp)
# contigs (>= 25000 bp)
# contigs (>= 50000 bp)
Total length (>= 0 bp)
Total length (>= 1000 bp)
Total length (>= 5000 bp)
Total length (>= 10000 bp)
Total length (>= 25000 bp)
Total length (>= 50000 bp)
# contigs
Largest contig
Total length
N50
N75
L50
L75
# N's per 100 kbp
```

The current report parsing script isn't that intelligent though. I may be able to update it to support any N/L metric, just using a few simple regexes.

**Comment by dfornika** [comment]
Ah, I think I may see what the issue is. This pipeline uses QUAST v5.0.2:

https://github.com/BCCDC-PHL/dragonflye-nf/blob/3833b24516782b6da42a1c6553e4429febd373fa/environments/environment.yml#L13

Other versions are not supported.

This pipeline is mostly intended for internal use at BCCDC-PHL. Of course you're welcome to use it if you find it useful. But in terms of supporting outside systems and environments we can't offer much.

If you're still interested in running this pipeline I'd suggest using the flags: `-profile conda --cache ~/.conda/envs`. That will build the conda env based on the `environment.yml` files in the repo, and the scripts should be consistent with the software versions in those environments.
